<?php

/*
 * This file is part of the Xivi package.
 *
 * (c) Praesidiarius <praesidiarius@proton.me>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace App\Command;

use App\Deployment\RegistryGrants;
use Symfony\Component\Console\Attribute\Argument;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Style\SymfonyStyle;

/**
 * Prints the SQL that leaves the customer-facing instance able to read the
 * registry and unable to write it (XIV-96, docs/architecture/deployment.md §4.4).
 *
 * ## Why this is a command rather than a file of SQL
 *
 * Because the answer changes when the registry does. `App\Registry` is the half
 * of the control-plane database a customer's request reads, adding an entity to
 * it is an ordinary thing to do, and a `grants.sql` checked in beside the
 * migrations would be right until the first time somebody did — after which the
 * public deployment would meet a permission error on a table nobody remembered
 * to list, at the worst possible moment, with a message that says nothing about
 * why. {@see RegistryGrants} asks the mapping instead, so the list is generated
 * from the same declarations the queries are.
 *
 * ## Why it prints instead of running
 *
 * Every statement here is one an application must not be able to issue about
 * itself. A running instance that could grant privileges could be made to grant
 * itself others, and the account these are run with is a database
 * administrator's rather than the application's. So the division of labour is:
 * the application knows *which tables*, a person with the right credentials
 * decides *whether*.
 *
 * It is deliberately safe to run against a production installation — it reads
 * mapping metadata and one connection parameter, and writes nothing anywhere.
 *
 * ## Exit codes
 *
 * Always 0. There is no failure this can report: it is asked a question about
 * this build's own mapping and always has an answer. The codes `deploy:check-hosts`
 * and `tenant:migrate` publish exist because those two can find something wrong
 * with an installation; this one cannot.
 *
 * The command that can is `deploy:check-grants` ([XIV-143]), which compares what
 * this prints against what the role is actually holding and exits 3 when they
 * differ. `bin/deploy` runs it on every release, because "run this again after a
 * release that adds a registry table" was previously a sentence in a changelog
 * and was missed twice in two days.
 *
 * @author Praesidiarius <praesidiarius@proton.me>
 */
#[AsCommand(
    name: 'deploy:registry-grants',
    description: 'Print the SQL that lets a customer-facing instance read the registry and write nothing',
)]
final readonly class RegistryGrantsCommand
{
    public function __construct(private RegistryGrants $grants)
    {
    }

    public function __invoke(
        SymfonyStyle $io,
        #[Argument(description: 'The database role the customer-facing instance connects as')]
        string $role = 'xivi_public',
    ): int {
        $io->writeln(sprintf(
            '-- The customer-facing instance connects as %s and must not be able to write the registry',
            $role,
        ));
        $io->writeln('-- (XIV-96, docs/architecture/deployment.md §4.4). Generated by `bin/console deploy:registry-grants`;');
        $io->writeln('-- run it again after any release that adds a registry table, because this list is');
        $io->writeln('-- read out of the mapping rather than maintained by hand.');
        $io->newLine();

        // The role itself is not created here, and the reason is one line long:
        // creating it means choosing a password, and a password chosen by a
        // command whose output goes to a terminal is a password in somebody's
        // shell history and in whatever collects their scrollback. So the shape
        // is shown and the secret is theirs to make.
        $io->writeln('-- The role has to exist first. If it does not:');
        $io->writeln(sprintf('--   CREATE ROLE "%s" LOGIN PASSWORD \'…\';', str_replace('"', '""', $role)));
        $io->newLine();

        foreach ($this->grants->statements($role) as $statement) {
            $io->writeln($statement);
        }

        $withheld = $this->grants->withheldTables();

        if ($withheld !== []) {
            $io->newLine();
            $io->writeln(sprintf(
                '-- Deliberately not granted, on any privilege: %s.',
                implode(', ', $withheld),
            ));
            $io->writeln('-- Those are the administration surface\'s own tables. The customer-facing image');
            $io->writeln('-- does not contain the code that reads them either, which is the point of');
            $io->writeln('-- having two builds; this is the half that holds if somebody deploys the wrong one.');
        }

        return Command::SUCCESS;
    }
}
