<?php

/*
 * This file is part of the Xivi package.
 *
 * (c) Praesidiarius <praesidiarius@proton.me>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace App\Tests\Functional\ControlPlane;

use App\Registry\Entity\Tenant;
use App\Registry\Repository\TenantRepository;
use App\Tenancy\TenantSwitcher;
use DAMA\DoctrineTestBundle\PHPUnit\SkipDatabaseRollback;
use Doctrine\DBAL\Connection;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Console\Tester\ApplicationTester;
use Symfony\Component\Console\Tester\CommandTester;
use Symfony\Component\HttpKernel\KernelInterface;
use Xivi\Contact\ContactModule;
use Xivi\ControlPlane\Provisioning\TenantProvisioner;
use Xivi\Core\Module\ModuleInstaller;
use Xivi\Core\Module\ModuleRegistry;

/**
 * The schema the migrations build is the schema the mapping describes (XIV-97).
 *
 * ## Why this is a test and not a habit
 *
 * `doctrine:schema:validate --em=control` reported the control-plane schema out
 * of sync for months, and the entire difference was three columns declared
 * `SERIAL` where Doctrine expected `GENERATED BY DEFAULT AS IDENTITY`. Nothing
 * was broken by it — the two behave near-identically — and that is exactly what
 * made it expensive: **a check that is always red is a check nobody reads**, so
 * the next time it went red for a real reason, because somebody added a property
 * to an entity and forgot the migration, it would have looked the same and been
 * scrolled past.
 *
 * Fixing the three columns without leaving something behind would have bought a
 * fortnight. This is the something: the day a mapping and a migration disagree,
 * `bin/ci` says so, by name, in the run that introduced it.
 *
 * ## The two databases are asked different questions, and not by choice
 *
 * **The control plane is asked the whole question**, in the literal words of the
 * acceptance criterion: `doctrine:schema:validate --em=control` is run and its
 * exit status is the assertion. Its schema is entirely Doctrine's — five tables,
 * all mapped — so a full comparison is a complete statement and "in sync" means
 * it.
 *
 * **A tenant is asked a narrower one**, because the whole question has no good
 * answer there and never will. A customer's database legitimately holds tables
 * Doctrine has never heard of: records are not entities (§5), so `contact`,
 * `article`, their history tables and their collection tables are built by
 * `ModuleInstaller` from that customer's own metadata, and `demo_record`,
 * `number_sequence` and `doctrine_migration_versions` are unmapped besides. An
 * unrestricted comparison proposes dropping all of them. So what is asserted out
 * there is the property this ticket actually established — that **no id column
 * anywhere draws from a `nextval()` default** — which is checkable, is exactly
 * the rule `tests/Unit/MigrationsUseIdentityColumnsTest.php` enforces at the
 * source, and holds for the module tables too.
 *
 * That is deliberately weaker than "the tenant schema is in sync", and it is
 * weaker because that is not true yet. `tenant:schema:validate` — the command
 * this ticket added, and the first way of asking the question at all — reports
 * thirteen further differences in a provisioned tenant: index names the entities
 * never declared, partial unique indexes the mapping cannot express, two column
 * defaults, and `shape_definition.parent_id`, where the mapping says `NOT NULL`
 * and the column is nullable because a module definition has no parent. Each of
 * those needs a decision rather than a conversion, so they are a ticket of their
 * own; asserting a green that is not there would have been the same mistake in
 * the other direction.
 *
 * ## Why it provisions its own customer
 *
 * `SharesATenant` leaves its database standing for the rest of the run, and this
 * class runs a command that walks tenants and closes the tenant connection under
 * DAMA's feet. Same reasoning as {@see TenantUsageCollectionTest}: this carries
 * `#[SkipDatabaseRollback]`, makes its own customer, and takes it away again.
 * The tenant is made once for the class rather than per test, because every test
 * here reads and none of them writes.
 *
 * @author Praesidiarius <praesidiarius@proton.me>
 */
#[SkipDatabaseRollback]
final class SchemaMatchesTheMappingTest extends KernelTestCase
{
    private const string SLUG = 'test_xiv97_schema';
    private const string HOST = 'schema-validation.localhost';

    /**
     * Every table whose `id` still gets its value from a sequence *default* —
     * which is what `SERIAL` compiles to and what an identity column does not
     * have.
     *
     * A table is absent from the answer for either of the two right reasons: its
     * id is an identity column, or it has no generated id at all —
     * `tenant_profile` is a singleton row at id 1 and declares no
     * `#[ORM\GeneratedValue]`, so it correctly has neither.
     */
    private const string SERIAL_COLUMNS = <<<'SQL'
        SELECT c.relname
          FROM pg_class c
          JOIN pg_attribute a ON a.attrelid = c.oid AND a.attname = 'id'
          JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = a.attnum
         WHERE c.relkind = 'r'
           AND c.relnamespace = 'public'::regnamespace
           AND pg_get_expr(d.adbin, d.adrelid) LIKE 'nextval(%'
         ORDER BY 1
        SQL;

    /** The same set, unfiltered: what the query above was given to look at. */
    private const string TABLES_WITH_AN_IDENTIFIER = <<<'SQL'
        SELECT c.relname
          FROM pg_class c
          JOIN pg_attribute a ON a.attrelid = c.oid AND a.attname = 'id'
         WHERE c.relkind = 'r'
           AND c.relnamespace = 'public'::regnamespace
         ORDER BY 1
        SQL;

    private static ?Tenant $tenant = null;

    protected function setUp(): void
    {
        // `SymfonyStyle::success()` wraps its block to the terminal, and the
        // assertions below read whole sentences out of that output. The same pin,
        // for the same reason, as {@see TenantUsageCollectionTest}.
        putenv('COLUMNS=240');

        self::bootKernel();
    }

    protected function tearDown(): void
    {
        putenv('COLUMNS');

        parent::tearDown();
    }

    public static function tearDownAfterClass(): void
    {
        self::bootKernel();
        self::removeFixture();
        self::$tenant = null;

        parent::tearDownAfterClass();
    }

    /**
     * The whole question, for the database that can answer it.
     *
     * The test control-plane database is built by running the migrations
     * (`tests/bootstrap.php`), which is what makes this meaningful rather than
     * circular — a database made by `doctrine:schema:create` would agree with the
     * mapping by construction and would prove nothing about the migrations.
     *
     * **It runs the real command through an `ApplicationTester` rather than
     * calling `SchemaValidator` directly**, and that is not ceremony. Doctrine's
     * migrations bundle hides `doctrine_migration_versions` from the comparison
     * with a listener that switches itself on when a `ValidateSchemaCommand` or
     * an `UpdateCommand` starts, and stays off otherwise — so a `SchemaValidator`
     * built by hand in a test proposes dropping the migrations table and reports
     * a drift nobody has. `CommandTester` is not enough either: it invokes the
     * command directly, and the listener is on `console.command`, which only the
     * application dispatches.
     *
     * The exit status is the assertion because it is the thing a person or a CI
     * job would read. The output goes into the failure message so that a red run
     * says which column, rather than that a number was not zero.
     */
    public function testTheControlPlaneSchemaIsInSyncWithTheMapping(): void
    {
        $kernel = self::$kernel;
        \assert($kernel instanceof KernelInterface);

        $application = new Application($kernel);
        $application->setAutoExit(false);

        $tester = new ApplicationTester($application);
        $status = $tester->run([
            'command' => 'doctrine:schema:validate',
            '--em' => 'control',
            // Doctrine prints the offending statements only above normal
            // verbosity, and they are the whole value of a failure here.
            '-v' => true,
        ]);

        self::assertSame(0, $status, $tester->getDisplay());
    }

    /** And the narrower one, for the same database, so the two agree. */
    public function testNoControlPlaneIdentifierIsASerialColumn(): void
    {
        $connection = self::service(Connection::class);

        self::assertContains('module', $this->tablesWithAnIdentifier($connection), 'the right database is open');
        self::assertSame([], $this->serialColumns($connection));
    }

    /**
     * The property that holds in every customer's database, including the tables
     * a module installs, which no list in this repository knows the names of.
     *
     * The first assertion is what stops the second being vacuous. A query for
     * "tables whose id is `SERIAL`" answers with an empty list just as
     * convincingly when it has been pointed at a database that has no tables at
     * all, and this one is created and torn down inside the test run — so the
     * cheapest way for this to become a check of nothing is for the provisioning
     * above to quietly stop happening. `contact` is asserted specifically because
     * it is installer-built rather than migration-built, which is the half the
     * source-level check cannot see.
     */
    public function testNoTenantIdentifierIsASerialColumn(): void
    {
        [$tables, $serial] = self::service(TenantSwitcher::class)->runFor(
            self::tenant(),
            fn (): array => [
                $this->tablesWithAnIdentifier(self::tenantConnection()),
                $this->serialColumns(self::tenantConnection()),
            ],
        );

        self::assertContains('app_user', $tables, 'the customer database was migrated');
        self::assertContains('contact', $tables, 'and a module was installed into it');

        self::assertSame([], $serial);
    }

    /**
     * **A tenant schema can be validated at all**, which before this ticket it
     * could not: `doctrine:schema:validate --em=tenant` has no tenant to resolve
     * and fails in the driver (docs/architecture/open-questions.md §7.4).
     *
     * What is asserted is that the command reaches a real customer's database and
     * reports on it by name — not that it finds nothing, because it still finds
     * the thirteen differences described in the class docblock. The day those are
     * dealt with, this is where the assertion tightens.
     */
    public function testATenantSchemaCanBeValidatedFromTheConsole(): void
    {
        self::tenant();

        $kernel = self::$kernel;
        \assert($kernel instanceof KernelInterface);

        $tester = new CommandTester((new Application($kernel))->find('tenant:schema:validate'));
        $tester->execute(['--slug' => self::SLUG]);

        $display = $tester->getDisplay();

        self::assertStringContainsString(self::SLUG, $display, 'the customer it reached is named');
        self::assertStringContainsString('The mapping files are correct.', $display);

        // The half this ticket did fix, asserted through the command rather than
        // through the catalogue, so that the two ways of asking cannot disagree.
        self::assertStringNotContainsString('ADD GENERATED BY DEFAULT AS IDENTITY', $display);
    }

    /**
     * The tables whose id is `SERIAL`, on whichever connection is passed.
     *
     * @return list<string>
     */
    private function serialColumns(Connection $connection): array
    {
        return $connection->executeQuery(self::SERIAL_COLUMNS)->fetchFirstColumn();
    }

    /**
     * Everything the query above had the chance to complain about.
     *
     * @return list<string>
     */
    private function tablesWithAnIdentifier(Connection $connection): array
    {
        return $connection->executeQuery(self::TABLES_WITH_AN_IDENTIFIER)->fetchFirstColumn();
    }

    /**
     * Made on first use and taken away in `tearDownAfterClass`.
     *
     * A module is installed into it, and that is the point rather than
     * decoration: `contact`, `contact_history` and `contact_address` are created
     * by `ModuleInstaller` out of the customer's own metadata rather than by any
     * migration, so they are the half of a tenant schema that no list in this
     * repository can enumerate — and the half a source-level check
     * ({@see \App\Tests\Unit\MigrationsUseIdentityColumnsTest}) can say nothing
     * about.
     *
     * Anything a previous run left under this slug goes first. The control plane
     * is not rolled back between tests — `CREATE DATABASE` cannot live in a
     * transaction, so the registry row cannot either — so a run that died halfway
     * would otherwise make the next one fail for a reason unrelated to the code.
     */
    private static function tenant(): Tenant
    {
        if (self::$tenant instanceof Tenant) {
            return self::$tenant;
        }

        self::removeFixture();

        self::$tenant = self::service(TenantProvisioner::class)
            ->provision(self::SLUG, 'Schema Validation', [self::HOST]);

        self::service(TenantSwitcher::class)->runFor(self::$tenant, static function (): void {
            self::service(ModuleInstaller::class)
                ->install(self::service(ModuleRegistry::class)->get(ContactModule::KEY));
        });

        return self::$tenant;
    }

    /** The customer, its database and its role, if any of them are there. */
    private static function removeFixture(): void
    {
        $existing = self::service(TenantRepository::class)->findOneBySlug(self::SLUG);

        if ($existing instanceof Tenant) {
            self::service(TenantProvisioner::class)->deprovision($existing);
        }
    }

    private static function tenantConnection(): Connection
    {
        $connection = self::getContainer()->get('doctrine')->getConnection(TenantSwitcher::CONNECTION);
        \assert($connection instanceof Connection);

        return $connection;
    }

    /**
     * @template T of object
     *
     * @param class-string<T> $id
     *
     * @return T
     */
    private static function service(string $id): object
    {
        $service = self::getContainer()->get($id);
        \assert($service instanceof $id);

        return $service;
    }
}
