<?php

declare(strict_types=1);

/*
 * **The bundles that may legitimately not be in this image** (XIV-96, XIV-111,
 * docs/architecture.md §4.4). A flat list of bundle class names, and nothing
 * else.
 *
 * `App\Kernel::getBundlesDefinition()` reads this list and drops any entry whose
 * class is not present in the build, so that `config/bundles.php` can name it
 * unconditionally. Everything below is *why the control plane is on the list*;
 * the rule that acts on it — why skipping is a `class_exists()` and why the list
 * is explicit rather than "skip anything missing" — is written out on that
 * method.
 *
 * ### Why this list is not inside `config/bundles.php`
 *
 * It used to be, as an `if (class_exists(…))` appending one key after the array.
 * Then `composer update xivi/voucher` ([XIV-103]) ran a Flex auto-recipe, which
 * regenerates `bundles.php` from its own template rather than editing it in
 * place, and the conditional was gone. It was caught in a diff and reverted, and
 * nothing was ever broken — but **adding a package is not an operation that
 * promises to leave `config/bundles.php` alone**, so a hand-written guard living
 * there was collateral by design rather than by accident.
 *
 * The fix is not to detect the rewrite. It is to make `bundles.php` a file whose
 * regenerated form is the form we want: a plain array, control-plane line
 * included, exactly the line Flex would write anyway. A recipe may now rewrite
 * it as often as it likes. This file is not generated by anything and has no
 * recipe that would ever touch it.
 *
 * ### Why the control plane is on it, and what that guarantee is
 *
 * `Dockerfile`'s `frankenphp_public` target removes `packages/control-plane`
 * outright ([XIV-96], §4.4), so in the customer-facing image the class below does
 * not exist and the kernel would fatal on `new $class()` before anything else got
 * a chance to fail. This is one of the three seams that make that image
 * buildable at all; the other two are `config/packages/security_firewalls.php`
 * and `config/routes/signup.php`, and
 * `tests/Unit/Deployment/ControlPlaneIsOptionalAtBuildTimeTest.php` holds the
 * list of all three.
 *
 * **The question asked is "is it in the image", never "is it switched on".** A
 * `%env()%` flag or an `if` on the environment would mean the administration
 * code is present and disabled, which is one misconfiguration away from being
 * served. [XIV-56] is the live precedent rather than a hypothetical: `.env.dev`
 * shipped inside the production image because an exclusion list needed a line
 * added and did not get one, and no amount of configuration would have kept it
 * out. Presence on disk is a fact two builds cannot disagree about.
 *
 * ### The bundle is appended, and that is a decision
 *
 * It is last in `config/bundles.php` rather than sitting between core and the
 * modules where it once did. Bundle order decides which bundle's
 * `prependExtension()` runs first and which one's templates win an override, and
 * this package neither overrides anything nor prepends anything another bundle
 * also prepends — see `XiviControlPlaneBundle::prependExtension()`, which
 * contributes the firewalls' provider and the entity mapping the application used
 * to declare on its behalf. Appending is also what a Flex recipe does with a
 * newly added bundle, so the position and the regeneration agree.
 *
 * ### Adding an entry here
 *
 * Do not, unless there is a build target that genuinely removes the package. An
 * entry is a promise that a missing class is *expected*, and every promise made
 * here is one more way for a broken `composer install` to look like a working
 * installation.
 */

return [
    Xivi\ControlPlane\XiviControlPlaneBundle::class,
];
