<?php

declare(strict_types=1);

namespace DoctrineMigrations\Tenant;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * A customer asks whoever runs their installation a question (XIV-123).
 *
 * The customer's half of the pair; `Version20260819122212` is the control-plane
 * half. **Which database this is in is not a preference.** A ticket is a write
 * made by a customer's own request, and §4.4 gives the customer-facing
 * instance's role `SELECT` on the registry tables and no write privilege
 * anywhere in the control-plane database, on any table, present or future. So a
 * feature whose first requirement is a write from a customer's request has
 * exactly one database available to it — this one — and an operator sees it
 * because `tenant:support:collect` copies it across. [XIV-102]'s
 * `module_purchase_intent` is here for the same sentence.
 *
 * The shape that removes the collector was rejected there and is rejected here:
 * an HTTP call to the control plane would hand the public image a credential
 * that writes that database, re-obtaining over the network exactly the privilege
 * PostgreSQL refuses it (§8.15, §8.17).
 *
 * ## What is deliberately not on this table
 *
 * **No status and no reply.** Both are the operator's, both live on the
 * control-plane copy, and the customer reads them back out of the registry —
 * which is what that grant has always permitted. So the *answer* needs no
 * collector and has no interval; only the question waits. Keeping a copy of the
 * status here as well would be two rows in two databases holding one fact, free
 * to disagree, and would need the collector to write *into* every customer's
 * database, which nothing does today.
 *
 * ## `reference`, and why it is not the id
 *
 * 128 random bits, generated when the row is made, and it is what the collected
 * copy is matched on. Ids are a sequence per database, so a customer whose
 * database is rebuilt starts again at 1 and a collector matching on the id would
 * overwrite the row holding an operator's answer to a different question. The
 * collector matches on `(tenant, reference)` rather than the reference alone, so
 * that one customer cannot name another's row by producing the same string.
 *
 * `raised_by_id` carries no foreign key, which is `follow_up`'s and
 * `module_purchase_intent`'s decision reused: nothing here should make removing
 * a person fail, and `raised_by_label` is what the screen draws. **Neither value
 * ever leaves this database** — an operator answers the company, on the screen
 * the company reads, and never learns which of a customer's staff typed it
 * (§8.11's line, [XIV-102]'s precedent).
 *
 * ## Cost and reversal
 *
 * **Costs an existing installation one empty table** and touches nothing else,
 * so it is additive in §4.2's sense: `bin/deploy` walks every customer with the
 * instance still serving, and a build that has not got this table simply has no
 * support page reaching it.
 *
 * **`down()` drops it and loses every question a customer has asked.** The
 * copies survive in the control plane, including the answers, so nothing an
 * operator wrote is lost — but the customer's own screen goes empty, and a
 * re-`up()` gives them a blank page rather than their history. That is the
 * honest reading of a table whose rows are the *source* and whose copies are
 * elsewhere.
 */
final class Version20260819122216 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'A customer raises a support ticket (XIV-123)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE support_ticket (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                reference VARCHAR(32) NOT NULL,
                subject VARCHAR(200) NOT NULL,
                body TEXT NOT NULL,
                raised_by_id INT DEFAULT NULL,
                raised_by_label TEXT NOT NULL,
                raised_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);

        // Unique because the reference is what the collected copy is matched on,
        // and two rows here claiming one reference would be two questions sharing
        // one answer. It is generated from `random_bytes(16)`, so this index is a
        // statement about the code rather than a constraint anybody will meet.
        $this->addSql('CREATE UNIQUE INDEX uniq_support_ticket_reference ON support_ticket (reference)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE support_ticket');
    }
}
