<?php

declare(strict_types=1);

namespace DoctrineMigrations\Tenant;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * A customer asks to buy a priced module (XIV-102).
 *
 * [XIV-101] gave a module a price; this is the half where somebody says they
 * want one. The store refuses to install a module that costs money and writes
 * this row instead, an operator sees it and either installs the module or gets
 * in touch. §8.15 has the argument, including the alternative that was rejected
 * — installing anyway and marking it unpaid — and the reason a *tenant's*
 * database is the only place this row could have gone.
 *
 * **That reason is [XIV-96]'s grant and not a preference** (§4.4). The
 * customer-facing image's database role holds `SELECT` on the registry tables
 * and nothing else — no `INSERT` anywhere in the control-plane database, on any
 * table — so a write made by a customer's own request has exactly one database
 * available to it and this is it. An operator sees these rows because
 * `tenant:purchase:collect` walks the customers one at a time and copies them
 * across, which is [XIV-59]'s answer to the same question about usage figures.
 *
 * **A new table rather than columns on anything.** There is nothing to hang it
 * off: the module in question is precisely the one this customer has *not* got,
 * so there is no `module_definition` row for it (§6.1) and could not be. That is
 * also why `module_key` is a plain string with no foreign key — it names a
 * catalogue key of the build, which is not a row in this database at all.
 *
 * **Costs an existing installation nothing.** It creates a table and touches no
 * other, so every customer's schema gains something no build before this one
 * looks at, which is what §4.2's additive rule is for: the deploy walks the
 * customer databases with the instance still serving, and for the length of that
 * walk one build of the code meets both schemas quite happily.
 *
 * **`down()` drops the table, and what it loses is real.** Every outstanding
 * purchase request, in a system that has no other record of them on the tenant's
 * side — the control plane's collected copies would survive and would then be
 * describing rows that no longer exist, which the next collection would tidy
 * away. Nobody is charged anything either way; what is lost is the queue, and
 * the customers in it will have to ask again.
 */
final class Version20260818150005 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'A customer asks to buy a priced module (XIV-102)';
    }

    public function up(Schema $schema): void
    {
        // `NUMERIC(12, 2)` for the amount, matching the `module` row this is a
        // copy of and every money column in the system (§5.9). The copy is
        // [XIV-101]'s instruction rather than this ticket's idea: a price is
        // frozen onto the request the way an invoice freezes its own totals, so
        // that raising a module's price tomorrow changes what the next customer
        // is quoted and not what this one was.
        //
        // The currency is nullable because `PRICE_CURRENCY` may legitimately be
        // unset, in which case the figure was shown bare and this row says so
        // rather than inventing a code nobody chose (§8.6, §6.5).
        $this->addSql(<<<'SQL'
            CREATE TABLE module_purchase_intent (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                module_key VARCHAR(63) NOT NULL,
                price_amount NUMERIC(12, 2) NOT NULL,
                price_currency VARCHAR(3) DEFAULT NULL,
                requested_by_id INT DEFAULT NULL,
                requested_by_label TEXT NOT NULL,
                requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);

        // One live request per module, enforced here rather than by a check in
        // the code — [XIV-109]'s rule, and the same argument: asking twice is
        // asking again, the store rewrites the row, and an index is what makes
        // that true for a request that arrives twice at once as well as for one
        // that arrives twice in a row.
        $this->addSql(
            'CREATE UNIQUE INDEX uniq_module_purchase_intent_module ON module_purchase_intent (module_key)',
        );

        // No foreign key on `requested_by_id`, which is `follow_up`'s decision
        // reused. A person who leaves must not take the record of a purchase
        // request with them, so the label is copied beside the id and the id is
        // allowed to stop resolving.
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE module_purchase_intent');
    }
}
