<?php

declare(strict_types=1);

namespace DoctrineMigrations\Tenant;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * A tenant remembers which recurring work already ran (XIV-155, §6.7).
 *
 * One table and one unique index, and the index is the feature. §6.7 gives the
 * engine a clock: a module declares work that recurs, cron calls
 * `tenant:work:run`, and the run has to survive being started twice: cron
 * overlapping itself, an operator typing the command by hand, a retry after a
 * kill. The answer is not "every module writes idempotent work", which is an
 * instruction nobody checks; it is this row, written in the same transaction as
 * the work, refused by `uniq_due_work_occurrence` when it already exists.
 *
 * **Engine bookkeeping in its own table**, the same shape `number_sequence` and
 * `voucher_redemption` have and for the same reasons. Nobody can rename it in the
 * editor, import over it or see it on a page; it is not a record and has no
 * shape. And it has no foreign key to whatever `subject` names, deliberately: a
 * customer deleting a recurring definition must not thereby make last month's
 * invoice due again, which is exactly what a cascade would do.
 *
 * ## The three columns that make one occurrence
 *
 * `job` is the declaration's key (`invoice.recurring`), `subject` is which record
 * it is about, and `period` is which occurrence: an instant, `timestamptz` like
 * every other moment in this application (§8.4.4), computed by the module in the
 * *tenant's* zone so that "the first of August" is the customer's first of August
 * and not the server's. `TIMESTAMP(0)`, so a period is a boundary rather than a
 * reading of a clock; `Xivi\Core\Schedule\DueWorkLog` says what happens to one
 * carrying a fraction of a second.
 *
 * `outcome` is `ran` or `passed`, and `passed` is the interesting one: it is an
 * occurrence a `CatchUp::OnlyTheLatest` declaration wrote off after an outage.
 * It has to be a row rather than a decision made and forgotten, because a module
 * answers "what is due" from its own records, which have not changed, so an
 * occurrence merely skipped would come back on every run for ever.
 *
 * `VARCHAR(63)` on the first two for the reason everything else in this schema
 * uses it: it is what a PostgreSQL identifier can be, so a key that fits a table
 * or column name fits here, and nothing in the engine can produce a longer one.
 *
 * Additive, like every tenant migration (§4.2). A new table is the easiest kind
 * of additive there is: the build running *before* this lands during the deploy
 * walk does not know the table exists and never names it.
 *
 * `down()` drops it, and dropping it means every occurrence the clock has run is
 * forgotten, so the next run finds a two-year-old monthly definition entirely
 * outstanding and bills it all again. That is the honest consequence of going
 * backwards past a feature whose whole content is a memory, and it is the reason
 * this paragraph exists rather than a reason to soften the `down()`.
 */
final class Version20260821151240 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'A tenant remembers which recurring work already ran';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE due_work (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                job VARCHAR(63) NOT NULL,
                subject VARCHAR(63) NOT NULL,
                period TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                outcome VARCHAR(15) NOT NULL,
                recorded_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        // The guarantee. Everything `DueWorkLog` promises is this index plus an
        // `ON CONFLICT … DO NOTHING` that names it: two runs reaching the same
        // occurrence at the same moment do not both insert, because the second
        // waits on the first's row lock and is then told there is nothing to do.
        // **Its column order is also the read order, which is why there is no
        // second index.** The runner asks "which of these have I already done"
        // once per job before it opens any transaction, filtering on `job` and
        // `subject`, the leading two columns of this index, because a module
        // re-offers every period it has ever produced on every run, and a
        // two-year-old monthly definition is twenty-four of them an hour. A
        // separate `(job, subject)` index would answer the same question with a
        // second thing to keep written on every insert.
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_due_work_occurrence ON due_work (job, subject, period)
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            DROP TABLE IF EXISTS due_work
            SQL);
    }
}
