<?php

declare(strict_types=1);

namespace DoctrineMigrations\Tenant;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * A reader puts an operator's notice away (XIV-120).
 *
 * The other half of §8.16, and the half that decides which database it is in.
 * The notice itself is a row in the control-plane database, read by everybody it
 * was addressed to; **dismissing one is a write, and a write made by a
 * customer's own request has exactly one database available to it** — theirs.
 * §4.4's grant gives the customer-facing instance `SELECT` on the registry and
 * no write privilege anywhere in that database, present or future, which is the
 * same sentence that put [XIV-102]'s purchase requests here and is the reason
 * this table is not two more columns over there.
 *
 * So the feature reads across the boundary and writes on this side of it, which
 * is the arrangement §4.4 was built to force.
 *
 * **One row per reader per notice, not per tenant.** Dismissing is *"I have read
 * this"*, and that is a fact about a person. A tenant-wide dismissal would let
 * whoever opened the dashboard first take a maintenance window off everybody
 * else's screen — which is precisely the silence the feature exists to end.
 *
 * **`notice_id` is a plain integer and has no foreign key it could have**, since
 * the row it names is in another database entirely. That makes it the same kind
 * of value as a saved dashboard layout's widget key (§8.3.1) or a stale
 * `reference` (§7.6): data pointing at something outside this database, resolved
 * where it is read and *dropped* rather than repaired when it resolves to
 * nothing. A dismissal of a notice that has been deleted hides nothing, which is
 * the correct behaviour and needs no cleanup — and there is deliberately no
 * process that goes looking for orphans, because the row is a few bytes and a
 * cross-database garbage collector is a much worse thing to own.
 *
 * `user_id` has no foreign key either, which is `follow_up`'s and
 * `module_purchase_intent`'s decision reused: nothing here should make removing
 * a person fail. Unlike those two there is no label copied beside it, because
 * nobody is ever shown who dismissed what — this row is read only by the person
 * who wrote it.
 *
 * **Costs an existing installation one empty table**, touches nothing else, and
 * is therefore additive in §4.2's sense: the deploy walks every customer with
 * the instance still serving, and a build that has not got this table simply
 * shows every notice.
 *
 * **`down()` drops it and un-dismisses everything.** Every notice a customer had
 * put away comes back on their dashboard, which is annoying and not dangerous —
 * and is the only reversible answer available, since the alternative is keeping
 * a table nothing reads.
 */
final class Version20260819103209 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'A reader dismisses a notice (XIV-120)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE notice_dismissal (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                notice_id INT NOT NULL,
                user_id INT NOT NULL,
                dismissed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);

        // Pressing dismiss twice — two tabs, a retyped POST, a double click — is
        // one dismissal. [XIV-109]'s rule: the index is what makes that true for
        // two requests that arrive at once as well as for two that arrive in a
        // row, and the writer treats the violation as "already done" rather than
        // as an error.
        $this->addSql('CREATE UNIQUE INDEX uniq_notice_dismissal ON notice_dismissal (notice_id, user_id)');

        // The reader's own query is "which of these notices have I put away",
        // which starts from the person. The unique index above answers it only
        // when the notice is known first, which is the other direction.
        $this->addSql('CREATE INDEX idx_notice_dismissal_user ON notice_dismissal (user_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE notice_dismissal');
    }
}
