<?php

declare(strict_types=1);

namespace DoctrineMigrations\Tenant;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Where a voucher's redemptions are counted (XIV-103).
 *
 * One row per voucher, holding how many times it has been used. A table rather
 * than a field on the record, and that is the decision this migration exists to
 * carry — the argument in full is in
 * `Xivi\Voucher\Redemption\VoucherRedemptions` and in docs/architecture.md
 * §5.19. The short version: a record is written by `RecordWriter` as one unit of
 * work, replacing the whole JSONB document, so two redemptions through that path
 * are two whole-document writes and the second overwrites the first's count. A
 * counter needs a statement whose `WHERE` can hold the limit, and a statement
 * like that needs a row that is about the count.
 *
 * The unique index is the whole safety mechanism, exactly as it is for
 * `number_sequence` (§5.10). Redemption is one statement —
 * `INSERT ... ON CONFLICT (voucher_id) DO UPDATE ... WHERE ... RETURNING` — and
 * the index is what turns the second of two simultaneous inserts into an update
 * of the first one's row, under a lock Postgres takes and PHP never sees. Without
 * it the statement is not merely slower, it is not a guard at all: two inserts
 * into a table with no unique index do not interact.
 *
 * ### Three things this deliberately does not do
 *
 * **No foreign key to `voucher`.** There cannot be one: a module's record table
 * is created per customer by the installer when they install the module (§6.1),
 * so at the moment this migration runs the table it would point at does not
 * exist in most databases and may never exist in some. The consequence is
 * honest and small — a counter row can outlive the voucher it counted — and it
 * is the same consequence records already have, since they are soft-deleted and
 * keep everything.
 *
 * **Created for every tenant, including those who will never install the
 * module.** An empty table with two columns is a cheaper thing to own than a new
 * engine concept ("a module may declare a side table") invented so that one
 * module can avoid it. `number_sequence` is in every tenant on the same terms,
 * including customers with no numbered field anywhere.
 *
 * **Nothing is backfilled**, because there is nothing to backfill: no tenant has
 * this module yet, and a voucher nobody has redeemed has no row by design —
 * "never used" and "no row" are the same statement about the world, which is why
 * `countFor()` reads zero out of an empty table rather than requiring a row to be
 * seeded when a voucher is created.
 *
 * `down()` drops the table and therefore every customer's redemption history
 * with it. That is what going backwards means here and it cannot be softened:
 * the counts exist nowhere else, so reversing this is a decision about data
 * rather than about schema.
 */
final class Version20260818150007 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add voucher_redemption: the guarded counter behind a voucher usage limit';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE voucher_redemption (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                voucher_id INT NOT NULL,
                redeemed_count INT NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);

        // Not merely an index: the ON CONFLICT target, and therefore the thing
        // that makes two simultaneous redemptions take turns instead of both
        // reading the same count. `tests/Functional/Engine/VoucherRedemptionRaceTest.php`
        // checks it is here under this name, because everything else in that file
        // passes just as convincingly against a table that is enforcing nothing.
        $this->addSql('CREATE UNIQUE INDEX uniq_voucher_redemption ON voucher_redemption (voucher_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE voucher_redemption');
    }
}
