<?php

declare(strict_types=1);

namespace DoctrineMigrations\Tenant;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * A list a customer keeps, and the entries in it (XIV-127).
 *
 * Two tables beside the field definitions rather than a module of its own, which
 * is §5.4's decision made physical. A module is the unit a customer *installs*:
 * it has a store entry, a price, permissions and records people browse. Nobody
 * browses a region. And the argument that settles it is §3's — a module may not
 * depend on another module, so a list that *contact*, *order* and *invoice*
 * fields all point at can only live where all three can see it, which is core.
 *
 * ## Why the entries are rows and not more JSON
 *
 * A `choice` field already keeps its options in its definition's `options` blob,
 * and the cheapest possible version of this ticket would have been a second blob
 * somewhere. It loses on the three things this ticket exists for. A colour and an
 * icon per entry are two more keys per option and would work; a **parent** is a
 * reference from one option to another, which JSON can express and nothing can
 * enforce; and "how many records hold this entry, across every module pointing
 * at this list" is a question you can answer against rows and cannot answer
 * against a blob without reading every field definition in the database and
 * parsing it. That last one is not a nicety — it is what every refusal and the
 * whole merge confirmation are built on (§5.4).
 *
 * ## `entry_value` is not unique here, deliberately
 *
 * It is unique *within a list*, which is what the unique index below says, and
 * that is the whole of the promise: two lists may both have a `standard`, and
 * they mean different things because they are in different lists. What every
 * record actually holds is this string, derived from the entry's first label and
 * then frozen, so that renaming an entry moves no record — XIV-144's rule for a
 * field's own options, applied here because §5.4 says a shared list is that
 * question with more records behind it.
 *
 * ## The two foreign keys point in different directions on purpose
 *
 * `list_id` cascades: an entry with no list is nothing, and deleting a list is
 * already refused while any field points at it, so the cascade only ever runs
 * over a list nothing can be holding a value from.
 *
 * `parent_id` is `ON DELETE SET NULL`, and it is the more interesting of the
 * two. An entry that loses its parent is still a perfectly good entry and every
 * record holding it is still valid; deleting the children with the parent would
 * take values out from under records that hold them, which is the one thing §5.4
 * refuses everywhere. Removing a parent that still has children is refused a
 * layer up anyway — this column says what the *database* would do if anything
 * ever got past that, and the answer is the survivable one rather than the tidy
 * one.
 *
 * ## Cost and reversal
 *
 * **Costs an existing installation two empty tables** and changes no existing
 * table, no existing column and no existing row. That is the strongest form of
 * §4.2's additive rule: `bin/deploy` walks the customer databases one at a time
 * with the instance still serving, and for the length of that walk one build of
 * the code meets both schemas — a build that has not got these tables simply has
 * no lists page, and every `choice` field in every tenant carries on exactly as
 * it did, because a field that names no list is the field this engine has always
 * had.
 *
 * **`down()` drops both and loses every list a customer built**, including the
 * colours and the hierarchy. It cannot do otherwise: the entries are the data.
 * Nothing in a *record* is lost by it — a record holds the entry's value as a
 * plain string in its own JSON, so the values survive and render raw, on the
 * same promise §5.4 makes for an option that has been removed. What goes is the
 * vocabulary, not the data.
 */
final class Version20260819172337 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'A list a customer keeps (XIV-127)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE value_list (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                list_key VARCHAR(63) NOT NULL,
                label VARCHAR(255) NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);

        // What a field definition names. Unique because a field's options hold
        // the key and nothing else, so two lists claiming one key would be two
        // lists one field could not choose between.
        $this->addSql('CREATE UNIQUE INDEX uniq_value_list_key ON value_list (list_key)');

        $this->addSql(<<<'SQL'
            CREATE TABLE value_list_entry (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                list_id INT NOT NULL,
                parent_id INT DEFAULT NULL,
                entry_value VARCHAR(63) NOT NULL,
                label VARCHAR(255) NOT NULL,
                tone VARCHAR(31) DEFAULT NULL,
                icon VARCHAR(63) DEFAULT NULL,
                position INT NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);

        // Unique within its list and nowhere else — see the class docblock.
        $this->addSql('CREATE UNIQUE INDEX uniq_value_list_entry_value ON value_list_entry (list_id, entry_value)');
        $this->addSql('CREATE INDEX idx_value_list_entry_parent ON value_list_entry (parent_id)');

        $this->addSql(<<<'SQL'
            ALTER TABLE value_list_entry
                ADD CONSTRAINT fk_value_list_entry_list FOREIGN KEY (list_id)
                REFERENCES value_list (id) ON DELETE CASCADE
            SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE value_list_entry
                ADD CONSTRAINT fk_value_list_entry_parent FOREIGN KEY (parent_id)
                REFERENCES value_list_entry (id) ON DELETE SET NULL
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE value_list_entry');
        $this->addSql('DROP TABLE value_list');
    }
}
