<?php

declare(strict_types=1);

namespace DoctrineMigrations\Tenant;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The same conversion as
 * {@see \DoctrineMigrations\ControlPlane\Version20260818090000}, in every
 * customer's database (XIV-97).
 *
 * **Read that file first.** Everything about *how* this works — why the three
 * lines `doctrine:schema:update --dump-sql` prints would break an installation
 * that has rows, why the old sequence has to be dropped between the default
 * going and the identity arriving, and which number is carried across — is
 * argued there at length and is not repeated here. What follows is only what is
 * different on this side.
 *
 * ## This is the larger half, and it was the unverified one
 *
 * The control plane is five tables in one database. This is eight tables in
 * *every customer's* database, and until this ticket nobody had checked whether
 * the drift was there, because the easy way to check does not work: a console
 * command has no resolved tenant (docs/architecture/open-questions.md §7.4), so
 * `doctrine:schema:validate --em=tenant` has nothing to connect to. It is
 * `tenant:schema:validate` that closes that gap — it enters each customer
 * through `TenantSwitcher::runFor()` and runs Doctrine's own validator inside —
 * and running it is how the drift below was established rather than assumed.
 *
 * ## Two of these eight tables are not entities, and are converted anyway
 *
 * Six of them back Doctrine entities and therefore *can* drift against a
 * mapping: `permission_group` and `permission_grant` (§8.4), `document_template`
 * (§5.7), `email_template` (§5.13), and `follow_up` with `follow_up_note`
 * ([XIV-80], §5.18). Those are what `tenant:schema:validate` complains about.
 *
 * `demo_record` and `number_sequence` are not mapped — a record is not a
 * Doctrine entity (§5), and these two are bookkeeping the engine reads with
 * DBAL — so no validator will ever mention them and converting them fixes
 * nothing that anybody can see.
 *
 * They are converted regardless, because the thing this ticket is actually
 * repairing is not six columns; it is that three hand-written migrations in a
 * row reached for `SERIAL` from memory. The rule that stops the fourth is *this
 * codebase does not use `SERIAL`*, and a rule with two exceptions in it is one
 * nobody can apply without first looking up which tables happen to be mapped.
 * Making the statement true everywhere is what lets
 * `tests/Unit/MigrationsUseIdentityColumnsTest.php` be a flat grep, with no list
 * of exempt tables in it for somebody to add a ninth name to.
 *
 * ## Two tenant tables are already right, and one is deliberately neither
 *
 * `app_user` was Doctrine-generated and has been an identity column since it was
 * created, as were `field_definition` and `shape_definition`. So were the record
 * tables a module installs — `contact`, `article`, their history tables and
 * their collection tables — because the installer builds those through
 * Doctrine's own schema tool rather than by hand, which is exactly the asymmetry
 * this ticket is about: the generated path was never wrong.
 *
 * `tenant_profile` has an `id INT` with no default and no sequence at all, and
 * that is correct rather than an omission: the row is a singleton at id 1 and
 * its entity declares no `#[ORM\GeneratedValue]`, so there is nothing to
 * generate. It is absent from the list below for that reason, and `up()` would
 * refuse to guess at it if it were not.
 */
final class Version20260818091000 extends AbstractMigration
{
    /**
     * Every table in a customer's database whose id came from `SERIAL`.
     *
     * A tenant database also holds one table per installed module plus their
     * history and collection tables, and none of those are here: the installer
     * creates them through Doctrine, so they have always been identity columns.
     * They are also not knowable from a migration — which modules a customer has
     * is a runtime fact about that customer (§3) — so a list is the only thing
     * this file could have contained even if they had needed converting.
     */
    private const array TABLES = [
        'demo_record',
        'document_template',
        'email_template',
        'follow_up',
        'follow_up_note',
        'number_sequence',
        'permission_grant',
        'permission_group',
    ];

    public function getDescription(): string
    {
        return 'Give every hand-written primary key an identity column, keeping its sequence position';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(self::toIdentity(self::TABLES));
    }

    public function down(Schema $schema): void
    {
        $this->addSql(self::toSerial(self::TABLES));
    }

    /**
     * `SERIAL` to `GENERATED BY DEFAULT AS IDENTITY`, sequence position intact.
     *
     * A copy of the control plane's, and deliberately a copy. A migration has to
     * keep working when the code around it has moved on, so a shared helper in
     * `src/` would be a file nobody may ever delete or change — the two are
     * frozen against different points in this repository's life and are supposed
     * to stay that way. The reasoning lives in the control-plane migration's
     * docblock and is not duplicated here.
     *
     * @param list<string> $tables
     */
    private static function toIdentity(array $tables): string
    {
        $list = self::sqlArray($tables);

        return <<<SQL
            DO $$
            DECLARE
                tbl     text;
                seq     text;
                next_id bigint;
            BEGIN
                FOREACH tbl IN ARRAY {$list} LOOP
                    -- Already an identity column: nothing to carry, nothing to drop.
                    CONTINUE WHEN (
                        SELECT a.attidentity::text FROM pg_attribute a
                         WHERE a.attrelid = tbl::regclass AND a.attname = 'id'
                    ) <> '';

                    seq := pg_get_serial_sequence(tbl, 'id');

                    -- Neither an identity nor a default drawn from a sequence.
                    -- Nothing here knows what that is, and inventing a starting
                    -- point for somebody's primary key is the one thing this
                    -- must not do.
                    IF seq IS NULL THEN
                        RAISE EXCEPTION '%.id has neither a sequence nor an identity; refusing to guess', tbl;
                    END IF;

                    -- `is_called` is false only for a sequence nothing has drawn
                    -- from yet, where `last_value` *is* the next value rather
                    -- than the previous one. That is the ordinary state of most
                    -- of these tables in most customers' databases: a tenant that
                    -- has never written a document template has never drawn from
                    -- `document_template_id_seq`.
                    EXECUTE format(
                        'SELECT GREATEST(
                             (SELECT last_value + CASE WHEN is_called THEN 1 ELSE 0 END FROM %s),
                             (SELECT coalesce(max(id), 0) + 1 FROM %I))',
                        seq, tbl
                    ) INTO next_id;

                    -- The order matters: the old sequence has to be gone before
                    -- the identity is added, or the new one is named
                    -- `<table>_id_seq1` and the orphan stays behind. `seq`
                    -- arrives from `pg_get_serial_sequence` already
                    -- schema-qualified and quoted, hence `%s` rather than `%I`.
                    EXECUTE format('ALTER TABLE %I ALTER COLUMN id DROP DEFAULT', tbl);
                    EXECUTE format('DROP SEQUENCE %s', seq);
                    EXECUTE format(
                        'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                        tbl, next_id
                    );
                END LOOP;
            END
            $$;
            SQL;
    }

    /**
     * The way back.
     *
     * More load-bearing here than in the control plane, because this one lands
     * in every customer's database at once (docs/architecture/deployment.md §4) — a change
     * that could only go forwards would have to be right the first time for all
     * of them simultaneously.
     *
     * @param list<string> $tables
     */
    private static function toSerial(array $tables): string
    {
        $list = self::sqlArray($tables);

        return <<<SQL
            DO $$
            DECLARE
                tbl     text;
                seq     text;
                next_id bigint;
            BEGIN
                FOREACH tbl IN ARRAY {$list} LOOP
                    CONTINUE WHEN (
                        SELECT a.attidentity::text FROM pg_attribute a
                         WHERE a.attrelid = tbl::regclass AND a.attname = 'id'
                    ) = '';

                    EXECUTE format(
                        'SELECT GREATEST(
                             (SELECT last_value + CASE WHEN is_called THEN 1 ELSE 0 END FROM %s),
                             (SELECT coalesce(max(id), 0) + 1 FROM %I))',
                        pg_get_serial_sequence(tbl, 'id'), tbl
                    ) INTO next_id;

                    seq := tbl || '_id_seq';

                    EXECUTE format('ALTER TABLE %I ALTER COLUMN id DROP IDENTITY', tbl);
                    EXECUTE format('CREATE SEQUENCE %I START WITH %s OWNED BY %I.id', seq, next_id, tbl);
                    EXECUTE format('ALTER TABLE %I ALTER COLUMN id SET DEFAULT nextval(%L)', tbl, seq);
                END LOOP;
            END
            $$;
            SQL;
    }

    /**
     * A PL/pgSQL `text[]` literal of table names.
     *
     * The names are this file's own constants rather than input from anywhere,
     * so there is nothing here to inject; the quoting exists so that the block
     * above reads as ordinary SQL instead of as string concatenation.
     *
     * @param list<string> $tables
     */
    private static function sqlArray(array $tables): string
    {
        return 'ARRAY[' . implode(', ', array_map(
            static fn (string $table): string => "'" . $table . "'",
            $tables,
        )) . ']';
    }
}
