<?php

declare(strict_types=1);

namespace DoctrineMigrations\Tenant;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The metadata tables: what modules and fields this customer has.
 *
 * These describe the shape of everything else, but their own shape is fixed, so
 * they are ordinary tables created by a migration. The tables they describe are
 * created per customer by the module installer instead — a module's table only
 * exists where that module is enabled (docs/architecture/deployment.md §4, §5).
 */
final class Version20260813192751 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the metadata tables (module_definition, field_definition)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE field_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, options JSON NOT NULL, field_key VARCHAR(63) NOT NULL, label VARCHAR(255) NOT NULL, field_type VARCHAR(63) NOT NULL, required BOOLEAN NOT NULL, is_unique BOOLEAN NOT NULL, filterable BOOLEAN NOT NULL, position INT NOT NULL, is_system BOOLEAN NOT NULL, module_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65B84660AFC2B591 ON field_definition (module_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_field_definition_module_key ON field_definition (module_id, field_key)');
        $this->addSql('CREATE TABLE module_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, installed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, module_key VARCHAR(63) NOT NULL, label VARCHAR(255) NOT NULL, table_name VARCHAR(63) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_module_definition_key ON module_definition (module_key)');
        $this->addSql('ALTER TABLE field_definition ADD CONSTRAINT FK_65B84660AFC2B591 FOREIGN KEY (module_id) REFERENCES module_definition (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE field_definition DROP CONSTRAINT FK_65B84660AFC2B591');
        $this->addSql('DROP TABLE field_definition');
        $this->addSql('DROP TABLE module_definition');
    }
}
