<?php

declare(strict_types=1);

namespace DoctrineMigrations\ControlPlane;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Somebody has asked for an installation, and nothing has been created for them
 * yet (XIV-64).
 *
 * **The only thing the public endpoint writes.** The naive shape of self-service
 * signup calls `TenantProvisioner::provision()`, which connects with the
 * credential its own docblock describes as *"allowed to CREATE DATABASE and
 * CREATE ROLE; provisioning only"* — one anonymous HTTP request away from the
 * most privileged operation in the system. So the endpoint records a row here
 * and stops. Turning one into a customer is [XIV-98], and it runs where an
 * operator can see it. docs/architecture/identity-and-access.md §8.12.
 *
 * ### Two unique indexes, and both of them are the feature
 *
 * `uniq_signup_request_email` is what makes a second submission a *replacement*
 * rather than a second row: one live signup per address, so "that mail never
 * arrived, let me try again" rewrites the row and kills the previous link
 * instead of piling up. Together with [XIV-98] removing the row when it
 * provisions, it is also "a confirmed address may hold one unprovisioned signup
 * at a time".
 *
 * `uniq_signup_request_reserved_slug` is the anti-squatting rule. `reserved_slug`
 * is NULL until an address has answered its confirmation mail, and PostgreSQL
 * treats NULLs in a unique index as distinct — so ten thousand unconfirmed
 * signups for `acme` collide with nothing and block nobody, while two *confirmed*
 * ones can never both hold it. Holding a name therefore costs a working mailbox,
 * per name.
 *
 * A partial unique index on `slug` — `WHERE status = 'confirmed'` — says the same
 * thing in SQL and was rejected for a reason that is not about SQL:
 * `doctrine:schema:validate` compares the mapping against the database, a partial
 * predicate does not survive that round trip intact, and a schema check that
 * reports a permanent false difference is a schema check people learn to ignore.
 *
 * ### `GENERATED BY DEFAULT AS IDENTITY`
 *
 * Not `SERIAL`, which is what three hand-written migrations in this directory
 * used and what [XIV-97] is repairing. The ORM's
 * `identity_generation_preferences` for PostgreSQL is `identity`, so a `SERIAL`
 * column is a permanent disagreement between the schema and the mapping — and
 * the sequence it creates is owned by the column in a way that behaves
 * differently on rename and on drop.
 *
 * ### Nothing is seeded, and nothing needs to be
 *
 * An empty table is exactly "nobody has asked yet", which is the correct state of
 * an installation that has just run this. It stays empty for good on a deployment
 * that leaves `SIGNUP_HOST` unset, because then there is no route to write to it.
 */
final class Version20260818000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Self-service signup requests, confirmed by email before they hold a name';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE signup_request (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                email VARCHAR(180) NOT NULL,
                company_name VARCHAR(255) NOT NULL,
                slug VARCHAR(63) NOT NULL,
                reserved_slug VARCHAR(63) DEFAULT NULL,
                plan VARCHAR(64) NOT NULL,
                locale VARCHAR(16) NOT NULL,
                status VARCHAR(16) NOT NULL,
                confirmation_token_hash VARCHAR(64) NOT NULL,
                confirmation_expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);

        $this->addSql('CREATE UNIQUE INDEX uniq_signup_request_email ON signup_request (email)');
        $this->addSql('CREATE UNIQUE INDEX uniq_signup_request_reserved_slug ON signup_request (reserved_slug)');

        // Every confirmation click is a lookup by this column, and it is the one
        // query on this table an anonymous request can cause. Not unique: two
        // rows sharing a SHA-256 of 32 random bytes is not a collision anybody
        // will see, and a unique index here would turn the astronomically
        // unlikely into an error page rather than into nothing.
        $this->addSql('CREATE INDEX idx_signup_request_token ON signup_request (confirmation_token_hash)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE signup_request');
    }
}
