<?php

declare(strict_types=1);

namespace DoctrineMigrations\ControlPlane;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The tenant registry: one row per customer, replacing per-domain .env files
 * (docs/architecture/deployment.md §4).
 */
final class Version20260813163549 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the tenant registry (tenant, tenant_domain)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE tenant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(32) NOT NULL, enabled_modules JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, provisioned_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, slug VARCHAR(63) NOT NULL, name VARCHAR(255) NOT NULL, database_dsn TEXT NOT NULL, plan VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_tenant_slug ON tenant (slug)');
        $this->addSql('CREATE TABLE tenant_domain (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, hostname VARCHAR(253) NOT NULL, is_primary BOOLEAN NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_86027A529033212A ON tenant_domain (tenant_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_tenant_domain_hostname ON tenant_domain (hostname)');
        $this->addSql('ALTER TABLE tenant_domain ADD CONSTRAINT FK_86027A529033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tenant_domain DROP CONSTRAINT FK_86027A529033212A');
        $this->addSql('DROP TABLE tenant');
        $this->addSql('DROP TABLE tenant_domain');
    }
}
