<?php

declare(strict_types=1);

namespace DoctrineMigrations\ControlPlane;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The whole control-plane schema, in one file (XIV-151).
 *
 * ## Squashed for the same reason and in the same commit as the tenant set
 *
 * This replaces the fourteen control-plane migrations written between
 * 2026-08-13 and 2026-08-19. The argument is
 * `migrations/tenant/Version20260819200755.php`'s and §4.2's and is not repeated
 * here: **nothing was deployed anywhere**, so no installation existed whose
 * schema had to be walked forward, so a migration's only remaining job was to
 * build a schema — which one file does as well as fourteen. The originals are in
 * git:
 *
 * ```
 * git log --diff-filter=D --name-only -- migrations/control
 * git show <the commit before>:migrations/control/Version20260818000000.php
 * ```
 *
 * **Doing the control plane in the same pass rather than leaving it was the
 * decision, and the reason is that half a squash is worse than neither half.**
 * The two sets share one numbering space (`MigrationVersionsAreUniqueTest`), one
 * `bin/new-migration`, one paragraph in AGENTS.md and one section of the brief.
 * Squashing only the tenant set would have left the repository explaining two
 * different things to the next author about what a migration is and how far back
 * its history goes, and would have left the second squash as a ticket that gets
 * written and never scheduled — by which time the window has closed on it too.
 * The control plane is one database rather than N, so it is the *easier* half;
 * that is a reason to do it now, not a reason to defer it.
 *
 * ## What is here and what is not
 *
 * There is nothing in this database that is not a table, an index or a
 * constraint: no extensions, no functions, no exclusion constraints, no
 * expression indexes. The tenant side needed `btree_gist` and two `IMMUTABLE`
 * functions before a period could be constrained; the control plane needs
 * nothing of the kind, and that asymmetry is worth stating so a reader does not
 * go looking for the missing half.
 *
 * Two names are Doctrine's rather than chosen — `idx_86027a529033212a` and
 * `fk_86027a529033212a` on `tenant_domain` — and they are kept exactly as they
 * are. They come from the one migration in this repository that was generated
 * rather than typed, and `tests/Functional/ControlPlane/SchemaMatchesTheMappingTest.php`
 * compares this schema against the mapping that produced them: spelling them
 * anything nicer would make that check red for ever, which is the failure XIV-97
 * spent a ticket undoing.
 *
 * As on the tenant side, the retro-fit migration (`Version20260818090000`,
 * XIV-97, which converted hand-written `SERIAL` primary keys to identity while
 * keeping each sequence's position) has nothing to do on an empty database. Its
 * conclusion is kept where it belongs: every `id` below is
 * `GENERATED BY DEFAULT AS IDENTITY`, which is what the mapping expects and what
 * keeps `doctrine:schema:validate --em=control` a check somebody still reads.
 *
 * `down()` drops the schema, which for a baseline is the honest reverse: there is
 * no earlier version of this database to return to.
 */
final class Version20260819200759 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'The control-plane schema, as one baseline (XIV-151)';
    }

    public function up(Schema $schema): void
    {
        // ---------------------------------------------------------------------
        // The registry: who exists, and how to reach their database (§4)
        // ---------------------------------------------------------------------
        //
        // `database_dsn` is the whole DSN minus the password, and it is stored
        // rather than derived from the slug because the two are allowed to
        // disagree — that is what `--dsn` on `tenant:provision` is for, and
        // `TenantProvisioner::deprovision()` resolves the database and the role
        // out of this column precisely so that a hand-made tenant can still be
        // removed by the command rather than by hand in psql (§4.1).
        //
        // `database_password` is separate and is a ciphertext, which is why it is
        // TEXT and not a bounded string: §8.9's cipher defends against somebody
        // holding a *copy* of this database, and the key is in
        // `TENANT_SECRET_KEYS` — which is one of the two secrets
        // `deploy:check-secrets` refuses to let an instance start on the public
        // value of (§4.2).
        //
        // `enabled_modules` is what the operator has sold them; what they have
        // actually installed is `tenant_usage.installed_modules`, collected from
        // the tenant's own database, and the two are allowed to differ (§6.1).
        $this->addSql(<<<'SQL'
            CREATE TABLE tenant (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                status VARCHAR(32) NOT NULL,
                enabled_modules JSON NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                provisioned_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                slug VARCHAR(63) NOT NULL,
                name VARCHAR(255) NOT NULL,
                database_dsn TEXT NOT NULL,
                plan VARCHAR(64) NOT NULL,
                database_password TEXT DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        // A tenant answers to one or more hostnames and exactly one of them is
        // primary — the one generated links are written with (§4.3). 253
        // characters because that is the longest a hostname is allowed to be.
        $this->addSql(<<<'SQL'
            CREATE TABLE tenant_domain (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                hostname VARCHAR(253) NOT NULL,
                is_primary BOOLEAN NOT NULL,
                tenant_id INT NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        // ---------------------------------------------------------------------
        // Operators and the module catalogue
        // ---------------------------------------------------------------------
        //
        // XIV-57, §8.1, §8.2. Somebody who can sign in to the administration
        // surface. `active` (XIV-92) is how an operator is revoked: deleting the
        // row was the alternative, and it loses the answer to "who approved this
        // signup in March". A revoked operator keeps their name on everything
        // they did and cannot sign in.
        $this->addSql(<<<'SQL'
            CREATE TABLE operator (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                email VARCHAR(180) NOT NULL,
                name VARCHAR(255) NOT NULL,
                password VARCHAR(255) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                active BOOLEAN NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        // XIV-7, §6.2. The platform-wide state of each module — whether it is
        // offered at all, and on what terms. `pricing` and `price_amount`
        // (XIV-101, XIV-102, §6.5) are the catalogue side of a purchase intent;
        // the amount is nullable because a free module has no price, which is a
        // different fact from a price of zero.
        $this->addSql(<<<'SQL'
            CREATE TABLE module (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                module_key VARCHAR(64) NOT NULL,
                state VARCHAR(32) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                pricing VARCHAR(32) NOT NULL,
                price_amount NUMERIC(12, 2) DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        // ---------------------------------------------------------------------
        // Self-service signup (XIV-64, XIV-98, §8.12)
        // ---------------------------------------------------------------------
        //
        // A request holds a name only once its email address has been confirmed,
        // which is what `reserved_slug` is for: `slug` is what they asked for and
        // `reserved_slug` is what is actually being held against them, so an
        // unconfirmed request cannot squat on a name. Nullable, and unique when
        // set.
        //
        // The token is stored as a hash, never as itself — the same rule as a
        // password, for the same reason: a copy of this table must not be a set of
        // working confirmation links.
        //
        // `provisioning_attempts`, `provisioning_failed_at` and
        // `provisioning_stage` (XIV-98) are what happened the last time a
        // confirmed signup failed to become a tenant. Without them a failure was
        // a log line on a machine nobody was looking at, and the customer's only
        // signal was that nothing arrived. `provisioning_stage` names *where* it
        // died, which is what decides whether a retry is safe.
        $this->addSql(<<<'SQL'
            CREATE TABLE signup_request (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                email VARCHAR(180) NOT NULL,
                company_name VARCHAR(255) NOT NULL,
                slug VARCHAR(63) NOT NULL,
                reserved_slug VARCHAR(63) DEFAULT NULL,
                plan VARCHAR(64) NOT NULL,
                locale VARCHAR(16) NOT NULL,
                status VARCHAR(16) NOT NULL,
                confirmation_token_hash VARCHAR(64) NOT NULL,
                confirmation_expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                provisioning_attempts INT DEFAULT 0 NOT NULL,
                provisioning_failed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                provisioning_stage VARCHAR(16) DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        // ---------------------------------------------------------------------
        // What is collected back out of the tenants (§8.11)
        // ---------------------------------------------------------------------
        //
        // XIV-58, XIV-59, XIV-95. One row per tenant, rewritten by a scheduled
        // collector. Every figure is nullable and there is a `failure` column,
        // because "we could not read this customer's database this morning" is a
        // thing that has to be *sayable*: the alternative is a zero, which reads
        // as a customer who has stopped using the product.
        //
        // `installed_modules` is what they actually have, against
        // `tenant.enabled_modules` which is what they are allowed to have (§6.1).
        $this->addSql(<<<'SQL'
            CREATE TABLE tenant_usage (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                tenant_id INT NOT NULL,
                collected_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                user_count INT DEFAULT NULL,
                last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                record_count INT DEFAULT NULL,
                records_by_module JSON DEFAULT NULL,
                failure TEXT DEFAULT NULL,
                installed_modules JSON DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        // XIV-102, §6.5. Purchase intents, collected out of each tenant's own
        // `module_purchase_intent` table so an operator can see who wants what
        // without opening a customer's database. `first_requested_at` is kept
        // alongside `requested_at` because "they have been asking since March" is
        // the fact that sells the module, and `installed` is how a collected
        // intent stops being a lead without being deleted.
        $this->addSql(<<<'SQL'
            CREATE TABLE purchase_intent (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                tenant_id INT NOT NULL,
                module_key VARCHAR(63) NOT NULL,
                price_amount NUMERIC(12, 2) NOT NULL,
                price_currency VARCHAR(3) DEFAULT NULL,
                requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                first_requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                installed BOOLEAN NOT NULL,
                collected_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        // XIV-123, §8.17. The control-plane copy of a customer's support ticket.
        // `reference` is unique *per tenant* rather than globally, because two
        // customers may each be looking at their ticket 7 and neither should have
        // to quote a number they have never seen. The reply lives here and is
        // carried back, which is why `reply`, `replied_at` and
        // `reply_author_label` are nullable: most tickets have not been answered
        // yet, and the author is a label for the reason the tenant side gives —
        // the operator who wrote it may have been revoked since.
        $this->addSql(<<<'SQL'
            CREATE TABLE support_request (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                tenant_id INT NOT NULL,
                reference VARCHAR(32) NOT NULL,
                subject VARCHAR(200) NOT NULL,
                body TEXT NOT NULL,
                raised_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                collected_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                status VARCHAR(32) NOT NULL,
                reply TEXT DEFAULT NULL,
                replied_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                reply_author_label TEXT DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        // XIV-120, §8.16. An operator writes a notice to customers.
        // `every_tenant` and the `notice_recipient` rows are the two ways of
        // saying who it is for, and they are not the same thing: "everybody,
        // including the customer who signs up tomorrow" cannot be expressed as a
        // list, and a list cannot be expressed as a flag. `author_label` rather
        // than an operator id, for the reason `operator.active` exists.
        $this->addSql(<<<'SQL'
            CREATE TABLE notice (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                title VARCHAR(200) NOT NULL,
                body TEXT NOT NULL,
                audience VARCHAR(32) NOT NULL,
                every_tenant BOOLEAN NOT NULL,
                author_label TEXT NOT NULL,
                published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE notice_recipient (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                notice_id INT NOT NULL,
                tenant_id INT NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        // ---------------------------------------------------------------------
        // Indexes
        // ---------------------------------------------------------------------
        //
        // `uniq_tenant_domain_hostname` is the one that matters most: a hostname
        // resolves to exactly one tenant, and the whole of tenancy is that lookup
        // (§4.3). `idx_86027a529033212a` keeps Doctrine's generated name for the
        // reason in the class docblock.
        //
        // `uniq_signup_request_email` and `uniq_signup_request_reserved_slug` are
        // what stop two people signing up as the same company at the same moment;
        // the second is unique over a nullable column, which is exactly the
        // behaviour wanted — many requests may hold no reservation, only one may
        // hold a given name.
        foreach ([
            'CREATE UNIQUE INDEX uniq_tenant_slug ON tenant (slug)',
            'CREATE UNIQUE INDEX uniq_tenant_domain_hostname ON tenant_domain (hostname)',
            'CREATE INDEX idx_86027a529033212a ON tenant_domain (tenant_id)',
            'CREATE UNIQUE INDEX uniq_operator_email ON operator (email)',
            'CREATE UNIQUE INDEX uniq_module_key ON module (module_key)',
            'CREATE UNIQUE INDEX uniq_signup_request_email ON signup_request (email)',
            'CREATE UNIQUE INDEX uniq_signup_request_reserved_slug ON signup_request (reserved_slug)',
            'CREATE INDEX idx_signup_request_token ON signup_request (confirmation_token_hash)',
            'CREATE UNIQUE INDEX uniq_tenant_usage_tenant ON tenant_usage (tenant_id)',
            'CREATE UNIQUE INDEX uniq_purchase_intent_tenant_module ON purchase_intent (tenant_id, module_key)',
            'CREATE UNIQUE INDEX uniq_support_request_reference ON support_request (tenant_id, reference)',
            'CREATE INDEX idx_support_request_tenant ON support_request (tenant_id)',
            'CREATE INDEX idx_support_request_raised ON support_request (raised_at)',
            'CREATE INDEX idx_notice_published ON notice (published_at)',
            'CREATE INDEX idx_notice_recipient_tenant ON notice_recipient (tenant_id)',
            'CREATE UNIQUE INDEX uniq_notice_recipient ON notice_recipient (notice_id, tenant_id)',
        ] as $statement) {
            $this->addSql($statement);
        }

        // ---------------------------------------------------------------------
        // Foreign keys
        // ---------------------------------------------------------------------
        //
        // Everything hangs off `tenant` and everything cascades. Removing a
        // customer removes their hostnames, their collected usage, their
        // collected intents, their support requests and their notice
        // targeting — none of which means anything without them, and all of which
        // `tenant:deprovision` would otherwise have to remember by hand (§4.1).
        foreach ([
            'ALTER TABLE tenant_domain ADD CONSTRAINT fk_86027a529033212a FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE',
            'ALTER TABLE tenant_usage ADD CONSTRAINT fk_tenant_usage_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE',
            'ALTER TABLE purchase_intent ADD CONSTRAINT fk_purchase_intent_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE',
            'ALTER TABLE support_request ADD CONSTRAINT fk_support_request_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE',
            'ALTER TABLE notice_recipient ADD CONSTRAINT fk_notice_recipient_notice FOREIGN KEY (notice_id) REFERENCES notice (id) ON DELETE CASCADE',
            'ALTER TABLE notice_recipient ADD CONSTRAINT fk_notice_recipient_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE',
        ] as $statement) {
            $this->addSql($statement);
        }
    }

    public function down(Schema $schema): void
    {
        foreach ([
            'notice_recipient', 'notice', 'support_request', 'purchase_intent',
            'tenant_usage', 'signup_request', 'module', 'operator',
            'tenant_domain', 'tenant',
        ] as $table) {
            $this->addSql(sprintf('DROP TABLE IF EXISTS %s', $table));
        }
    }
}
