<?php

declare(strict_types=1);

namespace DoctrineMigrations\ControlPlane;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Turn the three hand-written `SERIAL` primary keys into identity columns, so
 * that `doctrine:schema:validate --em=control` can go green (XIV-97).
 *
 * ## Why bother, when nothing is broken
 *
 * `SERIAL` and `GENERATED BY DEFAULT AS IDENTITY` behave near-identically —
 * both hand out numbers from a sequence, both let an explicit id through, and
 * no query in this codebase can tell them apart. So this migration changes no
 * behaviour whatsoever, and if it ever turns out to, that is a bug in it.
 *
 * What it buys is an instrument. `doctrine:schema:validate --em=control` has
 * reported *the database schema is not in sync with the current mapping file*
 * since the first hand-written migration landed, and the entire difference was
 * these three columns. A check that is always red is a check nobody reads: the
 * next time it goes red because somebody added a property to an entity and
 * forgot the migration, it will look exactly like this and be scrolled past.
 * Same argument [XIV-35] makes about a picker that truncates silently and
 * [XIV-59] about a failed collection reading as a zero — a signal that is
 * always on carries no information.
 *
 * The drift accumulated rather than being a single mistake, which is the part
 * worth naming. The *first* migration here was Doctrine-generated and wrote
 * `GENERATED BY DEFAULT AS IDENTITY` for `tenant` and `tenant_domain`. Every
 * hand-written one since reached for `SERIAL`, because that is what one types
 * from memory: `module`, then `operator` ([XIV-57]), then `tenant_usage`
 * ([XIV-59]). Two of those three were written on the same day. See `AGENTS.md`
 * and `tests/Unit/MigrationsUseIdentityColumnsTest.php` for what is meant to
 * stop the fourth.
 *
 * ## Why this is not the three lines `--dump-sql` prints
 *
 * `doctrine:schema:update --dump-sql --em=control` suggests exactly this:
 *
 *     ALTER TABLE module ALTER id DROP DEFAULT;
 *     ALTER TABLE module ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;
 *
 * **Running that would break every installation that has rows.** `ADD
 * GENERATED` creates a brand new sequence and it starts at 1, so the next
 * insert into a `module` table that already holds ten rows asks for id 1 and
 * dies on the primary key. `module` has rows in every installation where
 * anybody has ever set a module's state; `operator` has one the moment anybody
 * can sign in to the control plane at all; `tenant_usage` has one per customer
 * as soon as the nightly collection has run. So the current position of each
 * sequence has to be read *before* the old one goes and handed to the new one,
 * which is what the block below spends most of its length doing.
 *
 * There are three further things that dump does not tell you, all of them
 * measured on a real Postgres rather than reasoned about:
 *
 *   1. **`DROP DEFAULT` does not drop the sequence.** A `SERIAL` column's
 *      sequence is `OWNED BY` that column, and that ownership survives the
 *      default being removed. The sequence simply sits there, unreferenced,
 *      until the table is dropped.
 *   2. **Which means `ADD GENERATED` cannot have the obvious name.** With
 *      `module_id_seq` still occupying it, the identity sequence is created as
 *      `module_id_seq1`, and the database ends up carrying two sequences for
 *      one column where a freshly created one carries a single
 *      `module_id_seq`. That is a smaller version of exactly the untidiness
 *      this ticket exists to remove, and it would make an installation upgraded
 *      through this migration differ from a fresh one — the class of difference
 *      that makes a future migration behave differently in production than in
 *      the test that approved it.
 *   3. **And `pg_get_serial_sequence()` becomes ambiguous.** With both
 *      sequences present it kept answering `module_id_seq` — the orphan — even
 *      after the column had become an identity, because the old `OWNED BY`
 *      dependency is still the one it finds first. Anything written later that
 *      reaches for the column's sequence by that function would be handed the
 *      wrong one, silently.
 *
 * So the old sequence is dropped *between* the default going and the identity
 * arriving, and the identity sequence therefore gets the plain name a fresh
 * database would have given it.
 *
 * ## Which number is carried across
 *
 * `GREATEST(what the old sequence would hand out next, max(id) + 1)`.
 *
 * The sequence is the authoritative half and is usually ahead of `max(id)`: a
 * rolled-back insert or a deleted row consumes a number that no row is holding.
 * Taking `max(id) + 1` alone would re-issue those, which is harmless for a
 * primary key on its own and is not harmless for a number somebody has written
 * down elsewhere — an invoice reference in an email, a row in a log.
 *
 * `max(id) + 1` is the belt to that pair of braces. `SERIAL` permits an insert
 * that names its own id without advancing the sequence, so a table whose rows
 * were loaded from a dump — or seeded by a fixture that supplied ids — can hold
 * a `max(id)` far above its sequence. Starting the identity from the sequence
 * alone would then collide on the very first insert, which is the failure this
 * whole migration exists to avoid.
 *
 * ## Why one PL/pgSQL block rather than a list of `addSql()` lines
 *
 * The number above is a property of the database being migrated and cannot be
 * known when this file is written. Reading it into PHP and interpolating it
 * back would work for the control plane, which is one database — and the tenant
 * counterpart of this migration
 * ({@see \DoctrineMigrations\Tenant\Version20260818091000}) runs against every
 * customer's database in turn, where every one of them has a different answer.
 * Keeping the read and the write in one statement means the two cannot be
 * written differently, and means the value is never stale by the width of a
 * round trip.
 */
final class Version20260818090000 extends AbstractMigration
{
    /**
     * Every table in this database whose id came from `SERIAL`.
     *
     * `tenant` and `tenant_domain` are absent because they were generated by
     * Doctrine and have been identity columns since the day they were created.
     */
    private const array TABLES = ['module', 'operator', 'tenant_usage'];

    public function getDescription(): string
    {
        return 'Give every hand-written primary key an identity column, keeping its sequence position';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(self::toIdentity(self::TABLES));
    }

    public function down(Schema $schema): void
    {
        $this->addSql(self::toSerial(self::TABLES));
    }

    /**
     * `SERIAL` to `GENERATED BY DEFAULT AS IDENTITY`, sequence position intact.
     *
     * The tenant migration converts the same way over a longer list of tables,
     * and carries its own copy of this on purpose: a migration has to keep
     * working when the code around it has moved on, so a shared helper in
     * `src/` would be a file nobody may ever delete or change. The reasoning is
     * in this docblock and is not repeated there.
     *
     * Idempotent by inspection rather than by luck: a column that is already an
     * identity is skipped. That matters because a database made by
     * `doctrine:schema:create` rather than by migrations — which is not how
     * anything here is provisioned, but is how somebody debugging one afternoon
     * will do it — already has identity columns everywhere.
     *
     * @param list<string> $tables
     */
    private static function toIdentity(array $tables): string
    {
        $list = self::sqlArray($tables);

        return <<<SQL
            DO $$
            DECLARE
                tbl     text;
                seq     text;
                next_id bigint;
            BEGIN
                FOREACH tbl IN ARRAY {$list} LOOP
                    -- Already an identity column: nothing to carry, nothing to drop.
                    CONTINUE WHEN (
                        SELECT a.attidentity::text FROM pg_attribute a
                         WHERE a.attrelid = tbl::regclass AND a.attname = 'id'
                    ) <> '';

                    seq := pg_get_serial_sequence(tbl, 'id');

                    -- Neither an identity nor a default drawn from a sequence.
                    -- Nothing here knows what that is, and inventing a starting
                    -- point for somebody's primary key is the one thing this
                    -- must not do.
                    IF seq IS NULL THEN
                        RAISE EXCEPTION '%.id has neither a sequence nor an identity; refusing to guess', tbl;
                    END IF;

                    -- `is_called` is false only for a sequence nothing has drawn
                    -- from yet, where `last_value` *is* the next value rather
                    -- than the previous one.
                    EXECUTE format(
                        'SELECT GREATEST(
                             (SELECT last_value + CASE WHEN is_called THEN 1 ELSE 0 END FROM %s),
                             (SELECT coalesce(max(id), 0) + 1 FROM %I))',
                        seq, tbl
                    ) INTO next_id;

                    -- The order matters and is argued for in the class docblock:
                    -- the old sequence has to be gone before the identity is
                    -- added, or the new one is named `<table>_id_seq1` and the
                    -- orphan stays behind. `seq` arrives from
                    -- `pg_get_serial_sequence` already schema-qualified and
                    -- quoted, hence `%s` rather than `%I`.
                    EXECUTE format('ALTER TABLE %I ALTER COLUMN id DROP DEFAULT', tbl);
                    EXECUTE format('DROP SEQUENCE %s', seq);
                    EXECUTE format(
                        'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                        tbl, next_id
                    );
                END LOOP;
            END
            $$;
            SQL;
    }

    /**
     * The way back, which is a real requirement here rather than a formality.
     *
     * Every schema change lands for every installation (docs/architecture/deployment.md
     * §4), so one that cannot be undone is one somebody is stuck with at the
     * worst possible moment. This carries the position across by the same rule
     * and in the same direction, so `up()` followed by `down()` leaves a
     * database where it started rather than merely in a shape that resembles it.
     *
     * `DROP IDENTITY` takes the identity's own sequence with it — that one is an
     * *internal* dependency rather than an `OWNED BY` one, which is precisely
     * the asymmetry that makes `up()` longer than this.
     *
     * @param list<string> $tables
     */
    private static function toSerial(array $tables): string
    {
        $list = self::sqlArray($tables);

        return <<<SQL
            DO $$
            DECLARE
                tbl     text;
                seq     text;
                next_id bigint;
            BEGIN
                FOREACH tbl IN ARRAY {$list} LOOP
                    CONTINUE WHEN (
                        SELECT a.attidentity::text FROM pg_attribute a
                         WHERE a.attrelid = tbl::regclass AND a.attname = 'id'
                    ) = '';

                    EXECUTE format(
                        'SELECT GREATEST(
                             (SELECT last_value + CASE WHEN is_called THEN 1 ELSE 0 END FROM %s),
                             (SELECT coalesce(max(id), 0) + 1 FROM %I))',
                        pg_get_serial_sequence(tbl, 'id'), tbl
                    ) INTO next_id;

                    seq := tbl || '_id_seq';

                    EXECUTE format('ALTER TABLE %I ALTER COLUMN id DROP IDENTITY', tbl);
                    EXECUTE format('CREATE SEQUENCE %I START WITH %s OWNED BY %I.id', seq, next_id, tbl);
                    EXECUTE format('ALTER TABLE %I ALTER COLUMN id SET DEFAULT nextval(%L)', tbl, seq);
                END LOOP;
            END
            $$;
            SQL;
    }

    /**
     * A PL/pgSQL `text[]` literal of table names.
     *
     * The names are this file's own constants rather than input from anywhere,
     * so there is nothing here to inject; the quoting exists so that the block
     * above reads as ordinary SQL instead of as string concatenation.
     *
     * @param list<string> $tables
     */
    private static function sqlArray(array $tables): string
    {
        return 'ARRAY[' . implode(', ', array_map(
            static fn (string $table): string => "'" . $table . "'",
            $tables,
        )) . ']';
    }
}
