<?php

declare(strict_types=1);

namespace DoctrineMigrations\ControlPlane;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * An operator writes a notice, and customers read it (XIV-120).
 *
 * Whoever runs an installation had no way to say anything to the people using
 * it: a maintenance window, a module that gained a field, a trial about to end.
 * §8.16 has the argument; this is the table it lands in, and **which database it
 * is in is the whole decision**.
 *
 * **The registry half of the control-plane database, deliberately.** [XIV-102]
 * met the same boundary from the other side and had no choice: a purchase
 * request is a *write* made by a customer's own request, and §4.4's grant gives
 * the customer-facing instance `SELECT` and nothing else, so that row had to go
 * into the customer's own database and be collected. A notice is written by an
 * operator and only *read* by a customer — and reading the registry is precisely
 * what that grant already permits. So there is no collector here, no cron, no
 * interval and no copy: the notice is one row, in one place, read directly by
 * every instance that has to show it.
 *
 * That is why these two tables are `App\Registry\Entity` rather than
 * `Xivi\ControlPlane\Entity`, and it is not a matter of taste.
 * `App\Deployment\RegistryGrants` derives the readable list from the mapping by
 * asking for that namespace and no other, so an entity declared in the
 * administration surface's namespace would be on the *withheld* list — and the
 * customer-facing instance would meet SQLSTATE 42501 on the one query this
 * feature is for. `tests/Functional/Deployment/NoticeGrantsTest.php` runs the
 * reader as that role against this schema rather than trusting the paragraph.
 *
 * **Recipients are a table rather than a `ManyToMany`,** for that same
 * mechanical reason. A many-to-many's join table is not an entity, so it has no
 * metadata, so `readableTables()` cannot see it and would not grant it — a
 * boundary error that appears only on the deployment that matters, and only for
 * the customers a notice was addressed to by name. An entity is what the grant
 * generator can count.
 *
 * **`ON DELETE CASCADE` on both sides**, for `purchase_intent`'s reason word for
 * word: a deprovisioned customer's addressing is meaningless, and a foreign key
 * left behind turns a clean removal into a constraint violation somebody clears
 * by hand at exactly the wrong moment.
 *
 * **No `read_at`, no receipt table, and that is written down rather than
 * pending.** Knowing that somebody read a notice means collecting a fact out of
 * every customer's database, which is [XIV-102]'s collector pointed the other
 * way and is a feature rather than a column (§8.16).
 *
 * **`down()` drops both tables and loses every notice.** Nothing else holds
 * them: there is no copy in a tenant database, by design. What survives is the
 * customers' dismissals, which are rows in their own databases naming ids that
 * no longer resolve — and which are read as "nothing to hide" rather than as an
 * error, so a re-`up()` into an empty table is a working installation with no
 * announcements rather than a broken one.
 */
final class Version20260819103208 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'An operator writes a notice to customers (XIV-120)';
    }

    public function up(Schema $schema): void
    {
        // `every_tenant` rather than "no recipients means everybody", which is
        // the shape that reads the same and fails differently: an addressed
        // notice whose recipient rows were removed with a deprovisioned customer
        // would silently become an announcement to the entire installation. A
        // boolean says which of the two things somebody meant, and it cannot be
        // changed by a cascade.
        //
        // `audience` is who inside a tenant sees it — every user, or its
        // administrators — and it is per notice because a maintenance window is
        // everybody and a trial ending is the person who pays (§8.16). A short
        // string rather than a boolean, since a third audience is a plausible
        // thing to want and renaming a column is not.
        //
        // `author_label` is a copy of the operator's name and **not** a foreign
        // key to `operator`, which is the interesting one: the reader this
        // column exists for is a customer, and §4.4 gives the customer-facing
        // role no access to that table at all. A join would be unreadable by the
        // only party that needs the value. It is also the right answer for the
        // ordinary reason — an operator who is later revoked or renamed must not
        // rewrite the authorship of something already published.
        $this->addSql(<<<'SQL'
            CREATE TABLE notice (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                title VARCHAR(200) NOT NULL,
                body TEXT NOT NULL,
                audience VARCHAR(32) NOT NULL,
                every_tenant BOOLEAN NOT NULL,
                author_label TEXT NOT NULL,
                published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);

        // Every customer's dashboard asks the same question — what is live for
        // me, now — and the answer is bounded by these two columns before
        // anything else narrows it. `expires_at` is nullable and a notice with no
        // end is the common case, so the index is on the moment that always has
        // a value.
        $this->addSql('CREATE INDEX idx_notice_published ON notice (published_at)');

        $this->addSql(<<<'SQL'
            CREATE TABLE notice_recipient (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                notice_id INT NOT NULL,
                tenant_id INT NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);

        // One row per pair. Addressing the same customer twice on one notice is
        // not a second act of addressing them, and a duplicate would show up as
        // "2 customers" on the operator's screen — the one number that page
        // exists to state correctly.
        $this->addSql(
            'CREATE UNIQUE INDEX uniq_notice_recipient ON notice_recipient (notice_id, tenant_id)',
        );

        // The unique index above is useless to the reader's query, which starts
        // from a tenant and asks which notices name it. Column order in a
        // composite index is not a detail on the one query every dashboard runs.
        $this->addSql('CREATE INDEX idx_notice_recipient_tenant ON notice_recipient (tenant_id)');

        $this->addSql(<<<'SQL'
            ALTER TABLE notice_recipient
                ADD CONSTRAINT fk_notice_recipient_notice
                FOREIGN KEY (notice_id) REFERENCES notice (id)
                ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
            SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE notice_recipient
                ADD CONSTRAINT fk_notice_recipient_tenant
                FOREIGN KEY (tenant_id) REFERENCES tenant (id)
                ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE notice_recipient');
        $this->addSql('DROP TABLE notice');
    }
}
