<?php

declare(strict_types=1);

namespace DoctrineMigrations\ControlPlane;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The control plane collects purchase intents (XIV-102).
 *
 * The operator's half of "somebody wants to buy a module". The request itself is
 * written into the customer's own database — §4.4 gives the customer-facing
 * instance's role `SELECT` on the registry tables and no `INSERT` anywhere, so
 * that is the only database a customer's request can write — and
 * `tenant:purchase:collect` walks the customers one at a time and copies what it
 * finds into this table, which the operator screen then reads.
 *
 * **That is [XIV-59]'s shape and this table is `tenant_usage`'s sibling**: a row
 * here is a *collection* rather than a request, every value on it is qualified by
 * `collected_at`, and the page draws that moment beside the figures rather than
 * presenting them as current. The alternative — an operator page that opened
 * fifty tenant connections to build a list — is the one §8.11 argued out at
 * length, and the argument has not changed for being about a different question.
 *
 * **Why this table cannot be the one the customer writes.** It is in the
 * control-plane database. Granting the public role `INSERT` on it would mean
 * `RegistryGrantsTest` no longer being able to assert that the role holds no
 * write privilege anywhere, which is the guarantee [XIV-96] was for. The
 * separation costs a cron entry and buys a boundary a database enforces.
 *
 * **Costs nothing and starts empty.** No backfill: there is nothing to backfill
 * from, since no module has ever had a price a customer could be refused over.
 * A deployment that never runs the collector simply has an empty screen, which is
 * the honest reading of "nobody has asked for anything".
 *
 * **`down()` drops the table and loses only copies.** Every request it held is
 * still in the customer's own database and the next collection after a re-`up()`
 * finds them all again. That is a genuinely reversible migration, which is rarer
 * here than it looks and is a consequence of this table being derived rather than
 * authoritative.
 */
final class Version20260818150006 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Collected purchase intents, so an operator can see who wants what (XIV-102)';
    }

    public function up(Schema $schema): void
    {
        // The price is copied as it was shown to the customer, `NUMERIC(12, 2)`
        // like every other money column here and like the `module` row it came
        // from (§5.9, §6.5). The currency is nullable because `PRICE_CURRENCY`
        // may legitimately be unset, in which case the figure was shown bare.
        //
        // Two moments rather than one: `requested_at` is when they last asked
        // and `first_requested_at` is when they started asking, which is the
        // number that says how badly this has been left.
        $this->addSql(<<<'SQL'
            CREATE TABLE purchase_intent (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                tenant_id INT NOT NULL,
                module_key VARCHAR(63) NOT NULL,
                price_amount NUMERIC(12, 2) NOT NULL,
                price_currency VARCHAR(3) DEFAULT NULL,
                requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                first_requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                installed BOOLEAN NOT NULL,
                collected_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);

        // One row per customer per module, mirroring the unique index the
        // tenant-side table has on `module_key`. Two rows for one pair could
        // only ever mean the collector wrote twice, and an index is a cheaper
        // way to find that out than a support mail is.
        $this->addSql(
            'CREATE UNIQUE INDEX uniq_purchase_intent_tenant_module ON purchase_intent (tenant_id, module_key)',
        );

        // `ON DELETE CASCADE` for `tenant_usage`'s reason, word for word: a
        // deprovisioned customer's collected rows are meaningless and would
        // otherwise hold a foreign key against a row `deprovision()` is trying
        // to remove, turning a clean removal into a constraint violation
        // somebody clears by hand.
        $this->addSql(<<<'SQL'
            ALTER TABLE purchase_intent
                ADD CONSTRAINT fk_purchase_intent_tenant
                FOREIGN KEY (tenant_id) REFERENCES tenant (id)
                ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE purchase_intent');
    }
}
