<?php

declare(strict_types=1);

namespace DoctrineMigrations\ControlPlane;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * record signups refused as throwaway addresses
 *
 * XIV-125, §8.12. The signup endpoint now refuses an address whose provider is
 * on the throwaway list, and this is where those refusals are counted so that an
 * operator can see them. The argument for counting them at all is on
 * `Xivi\ControlPlane\Entity\SignupRefusal`: the list is a judgement, the
 * expensive way for it to be wrong is a real business being turned away, and the
 * only way anybody ever finds out is if the refusals appear somewhere a person
 * looks.
 *
 * **One row per domain, and the unique index is load-bearing rather than
 * hygienic.** The write is a single `INSERT … ON CONFLICT (domain) DO UPDATE`
 * issued from an anonymous internet-facing request, which is what makes two
 * simultaneous refusals safe and what keeps a failed write from closing the
 * entity manager the signup itself is using. Without `uniq_signup_refusal_domain`
 * that statement has nothing to conflict on and every refusal becomes a new row.
 *
 * **What this costs an installation that already has rows: nothing.** The table
 * is new and nothing back-fills it, so the counters begin at the moment this
 * runs and say so. There is no earlier data to lose, because before this ticket
 * a signup from a throwaway provider was accepted rather than refused, and the
 * evidence of one is a tenant on the list.
 *
 * **`down()` drops the table and the counts with it**, which is the honest
 * behaviour and is worth knowing before reversing: the rows are a tally rather
 * than a record of anything a person did, nothing references them, and no
 * feature reads them but one section of the tenant list. Reversing loses how
 * often each provider has been turned away and nothing else.
 */
final class Version20260820123040 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'record signups refused as throwaway addresses';
    }

    public function up(Schema $schema): void
    {
        // `GENERATED BY DEFAULT AS IDENTITY` rather than `SERIAL`, which is what
        // Doctrine's mapping expects and what keeps this table out of
        // `doctrine:schema:validate`'s permanent difference list (XIV-97).
        $this->addSql(<<<'SQL'
            CREATE TABLE signup_refusal (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                domain VARCHAR(255) NOT NULL,
                attempts INT DEFAULT 0 NOT NULL,
                first_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        $this->addSql('CREATE UNIQUE INDEX uniq_signup_refusal_domain ON signup_refusal (domain)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE signup_refusal');
    }
}
