<?php

/*
 * This file is part of the Xivi package.
 *
 * (c) Praesidiarius <praesidiarius@proton.me>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace App\Tests\Unit;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * No migration written from XIV-97 onwards creates a `SERIAL` column.
 *
 * ## What went wrong, and why a note would not have been enough
 *
 * The first migration in this repository was Doctrine-generated and wrote
 * `GENERATED BY DEFAULT AS IDENTITY`. Every hand-written one after it reached
 * for `SERIAL` instead — eleven tables across two databases, three of them written
 * on a single day — because `SERIAL` is what a person types from memory and
 * nothing anywhere said not to.
 *
 * The consequence was not a broken column; `SERIAL` and identity behave
 * near-identically. It was that `doctrine:schema:validate --em=control` reported
 * the schema out of sync **permanently**, so the one check that would have said
 * *somebody added a property and forgot the migration* had been saying the same
 * thing every day for months and had stopped being read. XIV-97 converted the
 * columns; this stops the next author undoing it in a fortnight, which the
 * conversion on its own does not.
 *
 * A line in `AGENTS.md` says the same thing and is there too — but a convention
 * enforced only socially is one that survives exactly as long as everybody has
 * read the file, and this codebase has already run that experiment.
 *
 * ## Why it reads the source rather than a database
 *
 * The schema tests in `tests/Functional/ControlPlane/SchemaMatchesTheMappingTest.php`
 * check the outcome — that no id column in either database ends up drawing from
 * a `nextval()` default. This checks the *cause*, and the two are worth having
 * separately: the outcome test tells you a database is wrong and leaves you to
 * find out which of twenty-five migrations did it, while this one names the file
 * and fails in milliseconds without a container.
 *
 * It also catches the case the outcome test cannot: a migration that adds a
 * `SERIAL` column to a table nobody has provisioned yet on this branch.
 *
 * **PHP comments are stripped before the search**, using PHP's own lexer rather
 * than a regular expression over the text. Migrations in this repository argue
 * with themselves at length, and the two written for XIV-97 necessarily discuss
 * `SERIAL` by name in their docblocks — a check that could not tell prose from
 * SQL would have failed on the very migration that fixed the problem.
 *
 * @author Praesidiarius <praesidiarius@proton.me>
 */
final class MigrationsUseIdentityColumnsTest extends TestCase
{
    /**
     * `SERIAL`, `BIGSERIAL` and `SMALLSERIAL`, wherever they appear in code.
     *
     * Case-insensitive because SQL is: `serial` in a heredoc is the same column
     * type and would drift the schema exactly as far.
     */
    private const string SERIAL = '/\b(?:BIG|SMALL)?SERIAL\b/i';

    /**
     * The version this rule starts at — XIV-97's own conversion, inclusive.
     *
     * **Nothing in the repository is below this line any more, and the line
     * stays anyway.** It was drawn because the eleven `SERIAL` columns written
     * before XIV-97 were a record of what every installation had actually run,
     * and rewriting them would have made the conversion migration a no-op
     * everywhere the suite could see it. XIV-151 then squashed both sets to a
     * single baseline each — possible only because nothing was deployed, §4.2 —
     * and the argument that protected those eleven files went with them: there
     * is no installation whose history they describe, and the baselines create
     * every `id` as identity in the first place.
     *
     * Keeping the constant costs nothing and removing it would cost the next
     * reader the explanation above. What matters is that it no longer excuses
     * anything: every migration in the tree is newer than this and every one of
     * them is checked, which is the state this test always wanted and now
     * trivially has.
     */
    private const string FROM_VERSION = '20260818090000';

    /**
     * Every migration written since the rule existed, named by set and file so
     * that a failure says which one without opening anything.
     *
     * @return iterable<string, array{string}>
     */
    public static function migrationFiles(): iterable
    {
        foreach (['control', 'tenant'] as $set) {
            foreach (glob(\dirname(__DIR__, 2) . '/migrations/' . $set . '/*.php') ?: [] as $file) {
                $name = basename($file);

                // `Version20260818090000.php` — the digits are what the migrations
                // table stores and what orders a run, so comparing them as strings
                // is comparing the same thing Doctrine does.
                if (preg_match('/^Version(\d+)\.php$/', $name, $matches) !== 1) {
                    continue;
                }

                if ($matches[1] < self::FROM_VERSION) {
                    continue;
                }

                yield $set . '/' . $name => [$file];
            }
        }
    }

    /**
     * That there is anything to check at all.
     *
     * Without this, renaming the directory — or changing the file-name shape the
     * provider matches on — would empty it and leave the check below passing by
     * describing nothing. That is the failure XIV-60 found in `deptrac`, where
     * seven layers collected no files and reported no violations for four
     * months, and it is the same failure this whole ticket is about: a green that
     * means "not checked" is worse than a red one.
     */
    public function testThereAreMigrationsToCheck(): void
    {
        self::assertGreaterThan(1, iterator_count(self::migrationFiles()));
    }

    #[DataProvider('migrationFiles')]
    public function testAMigrationDoesNotCreateASerialColumn(string $file): void
    {
        $source = file_get_contents($file);
        self::assertIsString($source, sprintf('cannot read %s', $file));

        self::assertDoesNotMatchRegularExpression(
            self::SERIAL,
            self::withoutComments($source),
            sprintf(
                "%s names SERIAL outside a comment.\n\n"
                . "Write `id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL` instead. It is what\n"
                . "Doctrine's mapping expects and what a generated migration produces; the two behave\n"
                . "near-identically, so nothing breaks — but every SERIAL column shows up forever in\n"
                . "`doctrine:schema:validate`, and a check that is always red is a check nobody reads.\n\n"
                . "Comments are stripped before this runs, so discussing SERIAL in a docblock is fine.\n"
                . "If it is a migration *description* that tripped this, reword the sentence: the rule\n"
                . "is deliberately the blunt one, because a cleverer pattern is one somebody edges past.\n\n"
                . 'See AGENTS.md and migrations/control/Version20260818090000.php.',
                basename($file),
            ),
        );
    }

    /**
     * The file with its PHP comments removed, so that prose about `SERIAL`
     * cannot be mistaken for a column that is one.
     *
     * `token_get_all()` rather than a regular expression: comment syntax nested
     * inside a heredoc — and heredoc syntax inside a comment — are both things
     * these files contain, and PHP's own lexer is the only thing that reliably
     * tells them apart.
     */
    private static function withoutComments(string $source): string
    {
        $kept = '';

        foreach (token_get_all($source) as $token) {
            if (\is_array($token)) {
                if ($token[0] === \T_COMMENT || $token[0] === \T_DOC_COMMENT) {
                    continue;
                }

                $kept .= $token[1];

                continue;
            }

            $kept .= $token;
        }

        return $kept;
    }
}
